"""Database repositories — one module per table."""

from src.db.repositories.conversations import (
    count_conversations,
    create_conversation,
    delete_conversation,
    end_conversation,
    get_conversation,
    list_conversations,
    update_conversation,
)
from src.db.repositories.embeddings import (
    count_embeddings,
    decode_embedding,
    delete_message_embeddings,
    encode_embedding,
    get_message_embedding,
    list_embeddings,
    save_message_embedding,
)
from src.db.repositories.messages import (
    count_messages,
    create_message,
    get_message,
    list_messages,
)
from src.db.repositories.memories import (
    archive_memory,
    count_memories,
    count_memory_embeddings,
    create_memory,
    delete_memory_embeddings,
    get_memory,
    keyword_search_memories,
    list_memories,
    list_memory_embeddings,
    save_memory_embedding,
    update_memory,
)
from src.db.repositories.tasks import (
    count_tasks,
    create_task,
    delete_task,
    due_tasks,
    get_task,
    list_tasks,
    update_task,
)

__all__ = [
    "archive_memory",
    "count_conversations",
    "count_embeddings",
    "count_memories",
    "count_memory_embeddings",
    "count_messages",
    "count_tasks",
    "create_conversation",
    "create_memory",
    "create_message",
    "create_task",
    "decode_embedding",
    "delete_conversation",
    "delete_memory_embeddings",
    "delete_message_embeddings",
    "delete_task",
    "due_tasks",
    "encode_embedding",
    "end_conversation",
    "get_conversation",
    "get_memory",
    "get_message",
    "get_message_embedding",
    "get_task",
    "keyword_search_memories",
    "list_conversations",
    "list_embeddings",
    "list_memories",
    "list_memory_embeddings",
    "list_messages",
    "list_tasks",
    "save_memory_embedding",
    "save_message_embedding",
    "update_conversation",
    "update_memory",
    "update_task",
]
