"""create memories and memory embeddings tables

Revision ID: 691551621438
Revises: a30d9176e2bb
Create Date: 2026-08-09 12:41:37.292320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '691551621438'
down_revision: Union[str, Sequence[str], None] = 'a30d9176e2bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('importance', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='memorystatus', native_enum=False, length=16), nullable=False),
    sa.Column('source_message_id', sa.Integer(), nullable=True),
    sa.Column('source_conversation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'archived')", name='ck_memories_status'),
    sa.CheckConstraint('importance BETWEEN 1 AND 10', name='ck_memories_importance'),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_category'), 'memories', ['category'], unique=False)
    op.create_index(op.f('ix_memories_status'), 'memories', ['status'], unique=False)
    op.create_table('memory_embeddings',
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_index(op.f('ix_memory_embeddings_model_name'), 'memory_embeddings', ['model_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_embeddings_model_name'), table_name='memory_embeddings')
    op.drop_table('memory_embeddings')
    op.drop_index(op.f('ix_memories_status'), table_name='memories')
    op.drop_index(op.f('ix_memories_category'), table_name='memories')
    op.drop_table('memories')
    # ### end Alembic commands ###
