"""create message embeddings table

Revision ID: a30d9176e2bb
Revises: c595cc6f6ea7
Create Date: 2026-08-09 00:37:03.706327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a30d9176e2bb'
down_revision: Union[str, Sequence[str], None] = 'c595cc6f6ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_embeddings',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_message_embeddings_model_name'), 'message_embeddings', ['model_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_embeddings_model_name'), table_name='message_embeddings')
    op.drop_table('message_embeddings')
    # ### end Alembic commands ###
