"""create tasks table

Revision ID: e6dab644bb8e
Revises: 691551621438
Create Date: 2026-08-10 22:28:31.920192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6dab644bb8e'
down_revision: Union[str, Sequence[str], None] = '691551621438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('model', sa.Enum('local', 'gemini', name='taskmodel', native_enum=False, length=16), nullable=False),
    sa.Column('schedule_type', sa.Enum('one_shot', 'interval', 'cron', name='taskscheduletype', native_enum=False, length=16), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('cron_expr', sa.String(length=64), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'done', name='taskstatus', native_enum=False, length=16), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=16), nullable=True),
    sa.Column('last_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("model IN ('local', 'gemini')", name='ck_tasks_model'),
    sa.CheckConstraint("schedule_type IN ('one_shot', 'interval', 'cron')", name='ck_tasks_schedule_type'),
    sa.CheckConstraint("status IN ('active', 'paused', 'done')", name='ck_tasks_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_model'), 'tasks', ['model'], unique=False)
    op.create_index(op.f('ix_tasks_next_run_at'), 'tasks', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_next_run_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_model'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
